"""Збирає yolo_test.ipynb: незалежний тест готової YOLO за ТЗ на Kaggle."""
import json, os, base64
D = os.path.dirname(os.path.abspath(__file__)); R = os.path.dirname(D); TP = f"{D}/team_package"
md = lambda s: {"cell_type": "markdown", "metadata": {}, "source": s}
code = lambda s: {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": s}
TEAM = open(f"{D}/team_data_cell.py").read()
FETCH = TEAM[TEAM.index("def fetch"):TEAM.index("# 1. Сирий архів")]
ADD_SUN = TEAM[TEAM.index("def add_sun"):TEAM.index("if SUN_FRAC")]
EVAL = open(f"{R}/yolo/eval_tz.py").read(); assert "'''" not in EVAL

cells = [
    md("# Тест YOLO за ТЗ кейсу 4.5\n\n"
       "Що робить: збирає **незалежний test** Anti-UAV410 SKY (54 серії, 21 551 кадр, модель їх не бачила) і val для вибору порогу, "
       "підбирає поріг на val, перевіряє на test окремо по наборах (небо, змішані сцени, порожні кадри, синтетичне сонце, "
       "SIRST-набори, якщо додані), рахує FPS, експортує TensorRT FP16 і перевіряє, що Recall не впав.\n\n"
       "**Перед запуском**\n"
       "1. Settings: Accelerator **GPU T4 x2** (працює одна), Internet **On**.\n"
       "2. **Add Input** → модель: Output ноутбука, де вчили (Your Work / Notebook Output), або датасет з `best.pt`. "
       "Ноутбук сам знайде `best.pt` у `/kaggle/input`. Можна замість цього дати посилання на Drive у `WEIGHTS_URL`.\n"
       "3. Необов'язково: Kaggle → Datasets → New Dataset, завантажити всі `sirst_part*.zip` в один датасет, і **Add Input** цей датасет (справжнє сонце, порожнє небо, точкові цілі).\n"
       "4. **Save Version → Save & Run All**. Займає ~1-1.5 год. Результат: `test_results.zip` в Output."),
    code("# ======= ПАРАМЕТРИ =======\n"
         "DRIVE_URL = 'https://drive.google.com/file/d/1zsdazmKS3mHaEZWS2BnqbYHPEcIaH5WR/view'   # сирий AntiUAV410.zip (якщо Quota exceeded, посилання на копію)\n"
         "WEIGHTS = ''        # порожньо = знайти best.pt у /kaggle/input\n"
         "WEIGHTS_URL = ''    # або посилання на best.pt на Google Drive\n"
         "FP_BUDGET = 0.7     # FP на кадр, наш запас до вимоги ТЗ <= 1\n"
         "TRT = True          # експорт TensorRT FP16 і повторна перевірка на test\n"
         "INT8 = False        # TensorRT INT8 (довше, може губити дрібні цілі)\n"),
    code("# ======= ПАКЕТ КОМАНДИ: builder і маніфест val (кожен 4-й кадр) + test (усі кадри) =======\n"
         "import os, base64\nos.makedirs('/tmp/dl/team_package', exist_ok=True)\n"
         "open('/tmp/dl/team_package/build_antiuav_yolo.py', 'w').write(r'''" + open(f"{TP}/build_antiuav_yolo.py").read() + "''')\n"
         "open('/tmp/dl/team_package/man_test.csv.gz', 'wb').write(base64.b64decode('"
         + base64.b64encode(open(f"{TP}/man_test.csv.gz", "rb").read()).decode() + "'))\n"
         "open('/kaggle/working/eval_tz.py', 'w').write(r'''" + EVAL + "''')\n"
         "print('записано')"),
    code("# ======= ДАНІ =======\n"
         "!nvidia-smi -L\n!pip install -q ultralytics \"pandas>=2.2\" \"Pillow>=10\" \"PyYAML>=6\" tqdm\n"
         "import os, re, glob, sys, json, zipfile, shutil, subprocess\nimport numpy as np, pandas as pd, cv2\n"
         "DL = '/tmp/dl'; PKG = '/tmp/dl/team_package'; os.makedirs(DL, exist_ok=True)\n"
         + FETCH +
         "RAW = f'{DL}/AntiUAV410.zip'\n"
         "local = [f for f in glob.glob('/kaggle/input/**/*.zip', recursive=True) if os.path.getsize(f) > 2**30 and 'anti' in os.path.basename(f).lower()]\n"
         "if local: RAW = local[0]; print('архів з Input:', RAW)\n"
         "else: fetch(DRIVE_URL, RAW)\n"
         "assert zipfile.is_zipfile(RAW), 'DRIVE_URL має вести на zip-архів Anti-UAV410'\n\n"
         "SRC = '/tmp/sky_test'\n"
         "if not os.path.exists(f'{SRC}/data.yaml'):\n"
         "    shutil.rmtree('/tmp/sky_check', ignore_errors=True); shutil.rmtree(SRC, ignore_errors=True)\n"
         "    r = subprocess.run(f'python {PKG}/build_antiuav_yolo.py --source {RAW} --manifest {PKG}/man_test.csv.gz --output /tmp/sky_check --check-only', shell=True)\n"
         "    if r.returncode != 0: raise SystemExit('Архів не збігається з маніфестом, див. /tmp/sky_check/preflight_errors.csv')\n"
         "    subprocess.run(f'python {PKG}/build_antiuav_yolo.py --source {RAW} --manifest {PKG}/man_test.csv.gz --output {SRC}', shell=True)\n"
         "    print('помилок збірки:', len(pd.read_csv(f'{SRC}/build_errors.csv')))\n\n"
         "# Сцена кожного кадру з маніфесту (AIR = чисте небо, MIXED = небо з хмарами/будинками/лісом на краю, GROUND)\n"
         "sys.path.insert(0, PKG); sys.path.insert(0, '/kaggle/working')\n"
         "from build_antiuav_yolo import output_stem\nimport eval_tz as E\n"
         "man = pd.read_csv(f'{PKG}/man_test.csv.gz', dtype={'sequence': str})\n"
         "META = {output_stem(r.sequence, int(r.frame_number)): dict(seq=r.sequence, scene=r.scene) for r in man.itertuples()}\n\n"
         "# Синтетичне сонце на кадрах test (інший seed, ніж у навчанні): кожен 10-й кадр з ціллю + усі порожні\n"
         + ADD_SUN +
         "SUN = '/tmp/sun_test'\n"
         "if not os.path.exists(SUN):\n"
         "    os.makedirs(f'{SUN}/images/test'); os.makedirs(f'{SUN}/labels/test'); rng = np.random.default_rng(1)\n"
         "    files = sorted(glob.glob(f'{SRC}/images/test/*.jpg'))\n"
         "    for i, p in enumerate(files):\n"
         "        n = os.path.basename(p)[:-4]; lab = open(f'{SRC}/labels/test/{n}.txt').read()\n"
         "        if lab.strip() and i % 10: continue\n"
         "        img = cv2.imread(p, 0); H, W = img.shape\n"
         "        centers = [(float(l.split()[1]) * W, float(l.split()[2]) * H) for l in lab.splitlines() if l.strip()]\n"
         "        cv2.imwrite(f'{SUN}/images/test/{n}.jpg', add_sun(img, centers, rng), [cv2.IMWRITE_JPEG_QUALITY, 95])\n"
         "        open(f'{SUN}/labels/test/{n}.txt', 'w').write(lab)\n\n"
         "# SIRST-набори skydet, якщо додано sirst_part*.zip (усі частини в один датасет)\n"
         "for f in glob.glob('/kaggle/input/**/sirst_*.zip', recursive=True): zipfile.ZipFile(f).extractall('/tmp/sirst')\n"
         "for l in glob.glob('/kaggle/input/**/list.txt', recursive=True):   # Kaggle сам розпаковує zip: зливаємо частини в одну папку\n"
         "    d = os.path.dirname(l); shutil.copytree(d, '/tmp/sirst/' + os.path.basename(d), dirs_exist_ok=True)\n"
         "SIRST = {os.path.basename(os.path.dirname(l)): os.path.dirname(l) for l in glob.glob('/tmp/sirst/**/list.txt', recursive=True)}\n"
         "print('SIRST:', {k: len(glob.glob(v + '/images/*')) for k, v in SIRST.items()})\n\n"
         "VAL = E.yolo_items(SRC, 'val', META)\n"
         "TEST = E.yolo_items(SRC, 'test', META)\n"
         "SETS = {'test_all': TEST,\n"
         "        'test_AIR': [it for it in TEST if META.get(it['name'], {}).get('scene') == 'AIR'],\n"
         "        'test_MIXED': [it for it in TEST if META.get(it['name'], {}).get('scene') == 'MIXED'],\n"
         "        'test_empty': [it for it in TEST if not it['gts']],\n"
         "        'test_sun_synth': E.yolo_items(SUN, 'test', META)}\n"
         "for k in ['sky_targets', 'no_targets', 'sun_real']:\n"
         "    if k in SIRST: SETS['sirst_' + k] = E.mask_items(SIRST[k])\n"
         "print('val', len(VAL), '|', {k: len(v) for k, v in SETS.items()})"),
    code("# ======= МОДЕЛЬ =======\n"
         "from ultralytics import YOLO\nimport logging; logging.getLogger('ultralytics').setLevel(logging.ERROR)   # без сотень попереджень у лозі\n"
         "if WEIGHTS_URL.startswith('http'): WEIGHTS = '/tmp/best.pt'; fetch(WEIGHTS_URL, WEIGHTS)\n"
         "if not WEIGHTS:\n"
         "    found = sorted(glob.glob('/kaggle/input/**/best.pt', recursive=True)); print('знайдено:', found)\n"
         "    assert found, 'Не знайшов best.pt: Add Input з моделлю або WEIGHTS_URL'\n"
         "    WEIGHTS = found[0]\n"
         "shutil.copy(WEIGHTS, '/kaggle/working/best.pt'); WEIGHTS = '/kaggle/working/best.pt'\n"
         "model = YOLO(WEIGHTS)\n"
         "NAME = os.path.basename(str(model.model.yaml.get('yaml_file', 'yolo'))).replace('.yaml', '')\n"
         "print('модель:', NAME, round(sum(p.numel() for p in model.model.parameters()) / 1e6, 1), 'M параметрів')"),
    md("## Поріг на val, перевірка на test\n"
       "Два варіанти порогу, обидва підібрані на val (FP ≤ FP_BUDGET і на всіх кадрах val, і на порожніх кадрах val):\n"
       "- **strict**: лише одна найупевненіша рамка на кадр (top-1). Тоді на жодному кадрі не буде більше 1 FP. На кадрі Anti-UAV410 не більше одної цілі.\n"
       "- **avg**: до 5 рамок на кадр, обмеження лише на середнє FP.\n\n"
       "`margin` = не брати рамки, що торкаються краю кадру (px)."),
    code("import time\nt0 = time.time()\n"
         "PV = E.predict(model, VAL)\n"
         "val_sets = {'val': (VAL, PV), 'val_empty': ([it for it in VAL if not it['gts']], [p for it, p in zip(VAL, PV) if not it['gts']])}\n"
         "CFG = {}\n"
         "for mode, topks in [('strict', [1]), ('avg', [1, 2, 3, 5])]:\n"
         "    b = E.tune(val_sets, FP_BUDGET, topks)\n"
         "    if b is None: b = (0, dict(conf=0.6, topk=1, margin=4), None); print(mode, 'УВАГА: FP > бюджету навіть при conf 0.6')\n"
         "    CFG[mode] = b[1]; print(mode, b[1], {k: (v['recall'], v['fp_per_frame']) for k, v in (b[2] or {}).items()})\n"
         "PRED = {k: E.predict(model, v) for k, v in SETS.items()}\n"
         "RES = {mode: {k: E.score(SETS[k], PRED[k], cfg) for k in SETS} for mode, cfg in CFG.items()}\n"
         "rows = [dict(config=m, set=k, **{c: v[c] for c in ['frames', 'targets', 'recall', 'fp_per_frame', 'fp_max', 'frames_fp_gt1']}) for m in RES for k, v in RES[m].items()]\n"
         "TABLE = pd.DataFrame(rows); print(f'{(time.time() - t0) / 60:.0f} хв'); TABLE"),
    code("# Recall за розміром цілі (більша сторона, px) і серії з найбільшою кількістю помилок (strict)\n"
         "print(pd.DataFrame({k: v['recall_by_size'] for k, v in RES['strict'].items()}).T)\n"
         "SEQ = pd.DataFrame(E.seq_table(TEST, PRED['test_all'], CFG['strict']))\n"
         "SEQ['scene'] = SEQ.sequence.map(man.drop_duplicates('sequence').set_index('sequence').scene)\n"
         "OUT = '/kaggle/working/test_results'; os.makedirs(OUT, exist_ok=True)\n"
         "E.gallery(TEST, PRED['test_all'], CFG['strict'], f'{OUT}/gallery')\n"
         "if 'test_sun_synth' in SETS: E.gallery(SETS['test_sun_synth'], PRED['test_sun_synth'], CFG['strict'], f'{OUT}/gallery_sun', n=8)\n"
         "SEQ.head(15)"),
    md("## Швидкість і TensorRT\nУвесь конвеєр на кадрі в пам'яті, batch 1: підготовка кадру, модель, NMS, наші фільтри. "
       "T4 ≈ 2080 SUPER за швидкістю в FP16 (2080 SUPER трохи швидша), тож цифри T4 близькі до фінальних."),
    code("SPEED = {'pytorch_fp32': E.speed(model, TEST, CFG['strict']), 'pytorch_fp16': E.speed(model, TEST, CFG['strict'], half=True)}\n"
         "KEY = [k for k in ['test_all', 'test_empty', 'test_sun_synth', 'sirst_sun_real', 'sirst_no_targets'] if k in SETS]\n"
         "for kind in (['fp16'] + (['int8'] if INT8 else [])) if TRT else []:\n"
         "    try:\n"
         "        kw = dict(half=True) if kind == 'fp16' else dict(int8=True, data=f'{SRC}/data.yaml', fraction=0.05)\n"
         "        eng = YOLO(WEIGHTS).export(format='engine', imgsz=[512, 640], batch=1, device=0, **kw)\n"
         "        dst = f'/kaggle/working/best_{kind}.engine'; shutil.move(eng, dst); m = YOLO(dst, task='detect')\n"
         "        SPEED['trt_' + kind] = E.speed(m, TEST, CFG['strict'])\n"
         "        for k in KEY:\n"
         "            r = E.score(SETS[k], E.predict(m, SETS[k], batch=1), CFG['strict'])\n"
         "            RES.setdefault('strict_trt_' + kind, {})[k] = r\n"
         "            print(kind, k, 'recall', r['recall'], '(PyTorch', RES['strict'][k]['recall'], ') FP', r['fp_per_frame'])\n"
         "    except Exception as e:\n"
         "        print('TensorRT', kind, 'не вдався:', repr(e)[:300])\n"
         "pd.DataFrame(SPEED).T"),
    code("# ======= ЗБЕРЕГТИ =======\n"
         "rep = dict(model=NAME, weights=WEIGHTS, gpu=(__import__('torch').cuda.get_device_name(0) if __import__('torch').cuda.is_available() else 'cpu'), fp_budget=FP_BUDGET, configs=CFG,\n"
         "           results=RES, speed=SPEED, notes=['Поріг підібрано на val, test не використовувався для вибору.',\n"
         "           'Влучання: центр рамки в рамці цілі +-3 px; Recall лише для цілей 5-50 px.',\n"
         "           'test_sun_synth зроблено тим самим генератором сонця, що й у навчанні: оцінка оптимістична. Справжнє сонце: sirst_sun_real.'])\n"
         "json.dump(rep, open(f'{OUT}/test_metrics.json', 'w'), indent=1, ensure_ascii=False)\n"
         "TABLE.to_csv(f'{OUT}/summary.csv', index=False); SEQ.to_csv(f'{OUT}/sequences.csv', index=False)\n"
         "# сирі передбачення test (conf >= 0.01): рядок = [номер кадру, x0, y0, x1, y1, conf], щоб потім перепідібрати пороги без моделі\n"
         "P = [np.hstack([np.full((len(p), 1), i, np.float32), p]) for i, p in enumerate(PRED['test_all'])]\n"
         "np.savez_compressed(f'{OUT}/pred_test.npz', names=np.array([it['name'] for it in TEST]), preds=np.vstack(P))\n"
         "shutil.make_archive('/kaggle/working/test_results', 'zip', OUT)\n"
         "print(json.dumps(dict(model=NAME, configs=CFG, speed=SPEED), ensure_ascii=False, indent=1))\n"
         "print(TABLE.to_string(index=False))"),
]
META = {"kernelspec": {"name": "python3", "display_name": "Python 3"},
        "kaggle": {"accelerator": "nvidiaTeslaT4", "isInternetEnabled": True, "isGpuEnabled": True}}
json.dump({"cells": cells, "metadata": META, "nbformat": 4, "nbformat_minor": 5}, open(f"{D}/yolo_test.ipynb", "w"), ensure_ascii=False, indent=1)
print("ok", os.path.getsize(f"{D}/yolo_test.ipynb") // 1024, "КБ")
